### ISSUE TITLE
Missing an argument for parameter 'DomainName'. Specify a parameter of type 'System.String' and try again

### ISSUE THREAD

**Issue by spuder** [NetDocuments/ad-join-cookbook#19]
Chef 12.19.33

Getting error `Missing an argument for parameter 'DomainName'. Specify a parameter of type 'System.String' and try again`

For some reason 'domain' attribute is getting overwritten. 

```ruby
10.254.60.126 [2017-02-22T19:16:17+00:00] INFO: Processing domain_join[default] action join (nd-ad-join::default line 31)
10.254.60.126 [2017-02-22T19:16:17+00:00] WARN: Cloning resource attributes for windows_task[chef ad-join] from prior resource
10.254.60.126 Previous windows_task[chef ad-join]: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:58:in `block in class_from_file'
10.254.60.126 Current  windows_task[chef ad-join]: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:72:in `block in class_from_file' (CHEF-3694)c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:72:in `block in class_from_file'.
10.254.60.126 Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
10.254.60.126 [2017-02-22T19:16:17+00:00] WARN: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:82:in `block (2 levels) in class_from_file': property domain is declared in both powershell_script[ad-join] and domain_join[default] action :join. Use new_resource.domain instead. At c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:82:in `block (2 levels) in class_from_file'
10.254.60.126 [2017-02-22T19:16:17+00:00] WARN: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:94:in `block (2 levels) in class_from_file': property domain is declared in both powershell_script[ad-join] and domain_join[default] action :join. Use new_resource.domain instead. At c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:94:in `block (2 levels) in class_from_file'
10.254.60.126 [2017-02-22T19:16:17+00:00] WARN: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:97:in `block (2 levels) in class_from_file': property domain is declared in both powershell_script[ad-join] and domain_join[default] action :join. Use new_resource.domain instead. At c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:97:in `block (2 levels) in class_from_file'
10.254.60.126 [2017-02-22T19:16:17+00:00] WARN: Cloning resource attributes for windows_task[chef ad-join] from prior resource
10.254.60.126 Previous windows_task[chef ad-join]: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:72:in `block in class_from_file'
10.254.60.126 Current  windows_task[chef ad-join]: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:113:in `block in class_from_file' (CHEF-3694)c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:113:in `block in class_from_file'.
10.254.60.126 Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
10.254.60.126 [2017-02-22T19:16:17+00:00] INFO: Processing ohai[reload] action reload (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 28)
```

**Comment by spuder** [comment]
Fixed in 4.12.0
