### ISSUE TITLE
vagrant provision failing

### ISSUE THREAD

**Issue by Prabhu13** [NetDocuments/ad-join-cookbook#38]
==> default: [2018-11-02T12:44:10+00:00] INFO: Running start handlers
==> default: [2018-11-02T12:44:10+00:00] INFO: Start handlers complete.
==> default: Running handlers:
==> default: [2018-11-02T12:44:12+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2018-11-02T12:44:12+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 05 seconds
==> default: [2018-11-02T12:44:12+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-11-02T12:44:12+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-11-02T12:44:12+00:00] ERROR: Cookbook 'seven_zip' version '3.1.0' depends on chef version [">= 13.0"], but the running chef version is 12.10.24
==> default: [2018-11-02T12:44:12+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by Prabhu13** [comment]
**stacktrace**

**Generated** at 2018-11-02 11:10:42 +0000
Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '3.1.0' depends on chef version [">= 13.0"], but the running chef version is 12.10.24
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/metadata.rb:721:in `validate_chef_version!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:54:in `block in validate!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:53:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:53:in `validate!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/expand_node_object.rb:77:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:508:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:278:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:51:in `load'
/usr/bin/chef-solo:51:in `<main>'

**Comment by Prabhu13** [comment]
Generated at 2018-11-02 11:10:42 +0000
Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '3.1.0' depends on chef version [">= 13.0"], but the running chef version is 12.10.24
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/metadata.rb:721:in `validate_chef_version!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:54:in `block in validate!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:53:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:53:in `validate!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/expand_node_object.rb:77:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:508:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:278:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:51:in `load'
/usr/bin/chef-solo:51:in `<main>'

**Comment by derekgroh** [comment]
You’re using an obsolete chef-client version, please consider upgrading. You will need to use at least version 13 to satisfy the constraints.
