### ISSUE TITLE
Doesn't display warning

### ISSUE THREAD

**Issue by spuder** [NetDocuments/ad-join-cookbook#4]
```
10.254.130.128 [2016-01-21T15:30:24-05:00] INFO:  * * * Computer is not joined to a domain * * *
10.254.130.128 [2016-01-21T15:30:24-05:00] INFO: Processing domain_join[default] action join (nd-ad-join::default line 31)
10.254.130.128 [2016-01-21T15:30:24-05:00] WARN: Cloning resource attributes for windows_task[chef ad-join] from prior resource (CHEF-3694)
10.254.130.128 [2016-01-21T15:30:24-05:00] WARN: Previous windows_task[chef ad-join]: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:55:in `block in class_from_file'
10.254.130.128 [2016-01-21T15:30:24-05:00] WARN: Current  windows_task[chef ad-join]: c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb:98:in `block in class_from_file'
10.254.130.128 [2016-01-21T15:30:24-05:00] INFO: Processing ohai[reload] action reload (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 25)
10.254.130.128 [2016-01-21T15:31:02-05:00] INFO: ohai[reload] reloaded
10.254.130.128 [2016-01-21T15:31:02-05:00] INFO: Processing reboot[Restart Computer] action nothing (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 32)
10.254.130.128 [2016-01-21T15:31:02-05:00] INFO: Processing registry_key[warning] action nothing (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 44)
10.254.130.128 [2016-01-21T15:31:02-05:00] INFO: Processing windows_task[chef ad-join] action create (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 55)
10.254.130.128 [2016-01-21T15:31:03-05:00] INFO: windows_task[\chef ad-join] task created
10.254.130.128 [2016-01-21T15:31:03-05:00] INFO: Processing powershell_script[ad-join] action run (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 65)
10.254.130.128 [2016-01-21T15:31:12-05:00] INFO: powershell_script[ad-join] ran successfully
10.254.130.128 [2016-01-21T15:31:12-05:00] INFO: powershell_script[ad-join] sending reboot_now action to reboot[Restart Computer] (immediate)
10.254.130.128 [2016-01-21T15:31:12-05:00] INFO: Processing reboot[Restart Computer] action reboot_now (c:/chef/cache/cookbooks/ad-join/resources/domain_join.rb line 32)
10.254.130.128 [2016-01-21T15:31:12-05:00] WARN: Rebooting system immediately, requested by 'Restart Computer'
10.254.130.128 [2016-01-21T15:31:12-05:00] INFO: Changing reboot status from {} to {:delay_mins=>0, :reason=>"Reboot by Chef", :timestamp=>2016-01-21 15:31:12 -0500, :requested_by=>"Restart Computer"}
10.254.130.128 [2016-01-21T15:31:13-05:00] INFO: Chef Run complete in 79.953125 seconds
10.254.130.128 [2016-01-21T15:31:13-05:00] INFO: Running report handlers
10.254.130.128 [2016-01-21T15:31:13-05:00] INFO: Report handlers complete
10.254.130.128 [2016-01-21T15:31:13-05:00] INFO: Sending resource update report (run-id: eed67856-f4f0-4311-8954-566d05882082)
10.254.130.128 [2016-01-21T15:31:13-05:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Reboot by Chef", :timestamp=>2016-01-21 15:31:12 -0500, :requested_by=>"Restart Computer"}

```

The warning message doesn't get displayed. 

Theories
- Delete notification is triggered even though it comes after the reboot resource
- only_if conditional is preventing the 'notify' from happening.

**Comment by spuder** [comment]
Should be fixed in v4.6.0

Cause: windows_task resource can't send notifications
https://github.com/chef-cookbooks/windows/issues/342
